name: Deploy to Amazon S3

on:
 push:
   branches:
     - main

jobs:
 Deploy:
   runs-on: ubuntu-latest
   steps:
     - run: ls -la
     - uses: actions/checkout@v2
     - run: ls -la
#      - name: Setup node
#        uses: actions/setup-node@v2

#      - name: Install dependencies
#        run: npm install

#      - name: Build static file
#        run: npm run build
#      - run: pwd
#      - run: mkdir build
#      - run: cp -R dist/apps/nx-react-github-actions/. build/
#      - run: ls -la
#      - run: pwd
#      - run: ls -la ./build/
#      - run: pwd
#      - run: echo "build done"
#      - run: name="Misha"
#      - run: echo "hello" $name

#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-s3-bucket: ${{ secrets.AWS_S3_BUCKET }}
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: us-east-1

#      - name: Deploy static site to S3 bucket
#        run: aws s3 sync ./build s3://nx-react-github-actions
